imap:
  pull:
    server: imap.gmail.com
    port: 993
  pull:
    server: imap.example.com
    port: 993
    # folder_delimiter: .
    # folder_name_mappings:
    #   "Envoyés": "Sent"
    #   "Corbeille": "Trash"
    #   "Pourriel": "Junk"